import fs from 'node:fs';
import assert from 'node:assert/strict';

const read=p=>fs.readFileSync(p,'utf8');
const index=read('public/index.html');
const css=read('public/styles.css');
const exact=read('public/reference-exact.css');
const liquid=read('public/liquid-menu.css');
const data=read('public/data.js');
const app=read('public/app.js');
const backup=read('public/backup-engine.js');
const cloud=read('public/cloud-adapter.js');
const sw=read('public/sw.js');
const manifest=read('public/manifest.webmanifest');
const wrangler=read('wrangler.jsonc');

for(const file of ['public/index.html','public/styles.css','public/target-ui.css','public/reference-exact.css','public/liquid-menu.css','public/app.js','public/data.js','public/backup-engine.js','public/storage-engine.js','public/cloud-adapter.js','public/manifest.webmanifest','public/icon.svg','public/reference-crest.webp','public/heritage-approved-full.webp','public/sw.js']) assert.ok(fs.existsSync(file),`missing ${file}`);
for(const retired of ['public/heritage-bg.svg','public/heritage-background.svg','public/heritage-background.webp','public/reference-polish.css','public/parchment-v4.css','public/final-polish.css','public/reference-hero.webp','public/reference-tree.webp','public/dongson-header.svg','public/tree-parchment.svg','public/hero-parchment.svg']) assert.ok(!fs.existsSync(retired),`retired visual layer must be deleted: ${retired}`);
assert.ok(!fs.existsSync('public/ui.js'),'legacy secondary UI runtime must be deleted');
for(const id of ['bottomNav','tree-view','familyTree','generationChips','members-view','events-view','documents-view','settings-view']) assert.ok(index.includes(`id="${id}"`),`missing #${id}`);
for(const view of ['overview','tree','members','events','documents','settings']) assert.ok(index.includes(`data-nav="${view}"`),`primary navigation missing ${view}`);
assert.ok(!index.includes('data-nav="more"'),'legacy Khác tab must be removed');
assert.ok(!index.includes('id="menuButton"'),'hamburger control must be removed');
assert.ok(!index.includes('id="drawer"'),'duplicate drawer navigation must be removed');
assert.ok(css.includes('.tree-connectors'),'SVG connector layer must be styled');
assert.ok(css.includes('.person-card.ancestor'),'ancestor card styling missing');
assert.ok(data.includes("/target-ui.css?v=4"),'geometry stylesheet must be v4');
assert.ok(data.includes("/reference-exact.css?v=18"),'approved visual stylesheet must be v18');
assert.ok(data.includes("/liquid-menu.css?v=12"),'navigation stylesheet must be v12');
assert.ok(data.includes("const approvedCrest='/reference-crest.webp?v=2'"),'approved crest must remain canonical');
assert.ok(data.includes("img.className='heritage-bg-image'"),'runtime must inject the single full background image node');
assert.ok(data.includes("img.src='/heritage-approved-full.webp?v=3'"),'runtime must use the approved full artwork directly');

assert.ok(exact.includes('.heritage-bg-image{'),'full heritage image node must be styled');
assert.ok(exact.includes('width:100%!important;height:auto!important'),'full heritage artwork must preserve natural vertical ratio');
assert.ok(exact.includes('opacity:.46!important'),'heritage artwork must be visually softened');
assert.ok(exact.includes('filter:saturate(.78) contrast(.86) brightness(1.08)!important'),'heritage artwork tone normalization missing');
assert.ok(exact.includes('transform:translate3d(0,0,0)!important'),'Safari compositing stabilization missing');
assert.ok(!exact.includes("background-image:url('/heritage-approved-full.webp"),'full heritage artwork must render as a DOM image, not CSS background');
assert.ok(!exact.includes('heritage-approved-top.webp'),'split top background must not render');
assert.ok(!exact.includes('heritage-approved-cont.webp'),'split continuation background must not render');
assert.ok(!exact.includes('heritage-background.svg'),'embedded-raster SVG must never render on Safari');
assert.ok(!exact.includes('heritage-background.webp'),'invalid temporary full background must not render');
assert.ok(fs.statSync('public/heritage-approved-full.webp').size>10000,'approved full heritage WebP asset looks invalid');
assert.ok(liquid.includes('position:fixed!important'),'bottom navigation must be viewport-fixed on Safari');
assert.ok(liquid.includes('grid-template-columns:repeat(6,minmax(0,1fr))'),'bottom navigation must use six equal tabs');
assert.ok(liquid.includes('@keyframes goldTabSweep'),'selected tab must retain the one-shot gold tracer');
assert.ok(liquid.includes('animation:goldTabSweep .9s'),'gold tracer must run once per selection');
for(const view of ['#overview-view','#tree-view','#members-view','#events-view','#documents-view','#settings-view']) assert.ok(exact.includes(view),`transparent shared-background view missing ${view}`);
assert.ok(exact.includes('background:transparent!important'),'views must expose the same continuous background');

assert.ok(app.includes('function renderTree'),'family tree renderer missing');
assert.ok(app.includes('function drawConnectors'),'coordinate connector renderer missing');
assert.ok(app.includes('renderAll(); bindEvents();'),'runtime must render before interaction binding');
assert.ok(backup.includes('schemaVersion'),'backup must include schema version');
assert.ok(backup.includes('snapshotCurrent'),'restore must snapshot current data');
assert.ok(cloud.includes('drive.appdata'),'Google Drive must use appDataFolder scope');
assert.ok(cloud.includes('resolveConflict'),'cloud conflicts must be explicit');
assert.ok(app.includes('appConfirm'),'destructive actions must use shared confirm');
assert.ok(!app.includes('window.confirm('),'native window.confirm is forbidden');
assert.ok(sw.includes("giaphaphamvan-v44"),'service worker cache version mismatch');
for(const asset of ['/target-ui.css?v=4','/reference-exact.css?v=18','/liquid-menu.css?v=12','/reference-crest.webp?v=2','/heritage-approved-full.webp?v=3','/data.js?v=8']) assert.ok(sw.includes(asset),`service worker missing ${asset}`);
assert.ok(!sw.includes('heritage-approved-top.webp'),'split top background must not be precached');
assert.ok(!sw.includes('heritage-approved-cont.webp'),'split continuation background must not be precached');
assert.ok(!sw.includes('heritage-background.svg'),'broken embedded SVG must not be precached');
assert.ok(sw.includes("cache:'no-store'"),'service worker must bypass stale HTTP artwork cache');
assert.ok(wrangler.includes('"directory": "./public"'),'Wrangler must deploy ./public');
assert.ok(manifest.includes('"theme_color": "#650912"')||manifest.includes('"theme_color": "#65080d"'),'PWA theme must be heritage red');
console.log('Giaphaphamvan softened seamless single heritage background v44 audit: PASS');
