import fs from 'node:fs';
import assert from 'node:assert/strict';

const read=p=>fs.readFileSync(p,'utf8');
const index=read('public/index.html');
const css=read('public/styles.css');
const exact=read('public/reference-exact.css');
const liquid=read('public/liquid-menu.css');
const data=read('public/data.js');
const app=read('public/app.js');
const backup=read('public/backup-engine.js');
const cloud=read('public/cloud-adapter.js');
const sw=read('public/sw.js');
const manifest=read('public/manifest.webmanifest');
const wrangler=read('wrangler.jsonc');

for(const file of ['public/index.html','public/styles.css','public/target-ui.css','public/reference-exact.css','public/liquid-menu.css','public/app.js','public/data.js','public/backup-engine.js','public/storage-engine.js','public/cloud-adapter.js','public/manifest.webmanifest','public/icon.svg','public/reference-crest.webp','public/heritage-approved-full.webp','public/sw.js']) assert.ok(fs.existsSync(file),`missing ${file}`);
for(const retired of ['public/heritage-bg.svg','public/heritage-background.svg','public/heritage-background.webp','public/reference-polish.css','public/parchment-v4.css','public/final-polish.css','public/reference-hero.webp','public/reference-tree.webp','public/dongson-header.svg','public/tree-parchment.svg','public/hero-parchment.svg']) assert.ok(!fs.existsSync(retired),`retired visual layer must be deleted: ${retired}`);
assert.ok(!fs.existsSync('public/ui.js'),'legacy secondary UI runtime must be deleted');
for(const id of ['bottomNav','tree-view','familyTree','generationChips','members-view','events-view','documents-view','settings-view']) assert.ok(index.includes(`id="${id}"`),`missing #${id}`);
for(const view of ['overview','tree','members','events','documents','settings']) assert.ok(index.includes(`data-nav="${view}"`),`primary navigation missing ${view}`);
assert.ok(!index.includes('data-nav="more"'),'legacy Khác tab must be removed');
assert.ok(!index.includes('id="menuButton"'),'hamburger control must be removed');
assert.ok(!index.includes('id="drawer"'),'duplicate drawer navigation must be removed');
assert.ok(index.includes('class="heritage-bg-image" src="/heritage-approved-full.webp?v=4"'),'canonical full background image must be present directly in HTML');
assert.ok(!index.includes('heritage-approved-top.webp'),'legacy top image must be removed from HTML');
assert.ok(!index.includes('heritage-approved-cont.webp'),'legacy continuation image must be removed from HTML');
assert.ok(index.includes('/data.js?v=9'),'index must load current visual runtime');
assert.ok(css.includes('.tree-connectors'),'SVG connector layer must be styled');
assert.ok(css.includes('.person-card.ancestor'),'ancestor card styling missing');
assert.ok(data.includes("/target-ui.css?v=4"),'geometry stylesheet must be v4');
assert.ok(data.includes("/reference-exact.css?v=21"),'approved visual stylesheet must be v21');
assert.ok(data.includes("/liquid-menu.css?v=14"),'navigation stylesheet must be v14');
assert.ok(data.includes("const approvedCrest='/reference-crest.webp?v=2'"),'approved crest must remain canonical');
assert.ok(data.includes("img.src='/heritage-approved-full.webp?v=4'"),'runtime must keep the approved full artwork canonical');
assert.ok(!data.includes("window.addEventListener('scroll'"),'Safari toolbar scroll events must not auto-hide navigation');
assert.ok(data.includes("if((window.scrollY||0)<80)return show()"),'nav must stay visible near the top');

assert.ok(exact.includes('.heritage-bg-image{'),'full heritage image node must be styled');
assert.ok(exact.includes('width:100%!important;height:auto!important'),'approved artwork must preserve its natural vertical ratio');
assert.ok(exact.includes('opacity:.58!important'),'heritage artwork visibility balance missing');
assert.ok(!exact.includes('filter:blur('),'approved artwork itself must remain unblurred');
assert.ok(exact.includes('-webkit-backdrop-filter:blur(9px)'),'cards must blur only the background behind the glass');
assert.ok(exact.includes('-webkit-backdrop-filter:blur(8px)'),'controls and tree cards must use translucent glass blur');
assert.ok(exact.includes('background:transparent!important'),'all views must expose the same underlying artwork');
assert.ok(exact.includes('.heritage-canvas>img:not(.heritage-bg-image)'),'legacy broken image placeholder must be suppressed');
assert.ok(!exact.includes('heritage-approved-top.webp'),'split top background must not render');
assert.ok(!exact.includes('heritage-approved-cont.webp'),'split continuation background must not render');
assert.ok(!exact.includes('heritage-background.svg'),'embedded-raster SVG must never render on Safari');
assert.ok(!exact.includes('heritage-background.webp'),'invalid temporary full background must not render');
assert.ok(fs.statSync('public/heritage-approved-full.webp').size>10000,'approved full heritage WebP asset looks invalid');
assert.ok(liquid.includes('position:fixed!important'),'bottom navigation must be viewport-fixed on Safari');
assert.ok(liquid.includes('-webkit-backdrop-filter:blur(16px)'),'bottom navigation must remain translucent Liquid Glass');
assert.ok(liquid.includes('-webkit-backdrop-filter:blur(12px)'),'top bar and selected tab must use Liquid Glass blur');
assert.ok(liquid.includes('grid-template-columns:repeat(6,minmax(0,1fr))'),'bottom navigation must use six equal tabs');
assert.ok(liquid.includes('@keyframes goldTabSweep'),'selected tab must retain the one-shot gold tracer');
assert.ok(liquid.includes('animation:goldTabSweep .9s'),'gold tracer must run once per selection');
for(const view of ['#overview-view','#tree-view','#members-view','#events-view','#documents-view','#settings-view']) assert.ok(exact.includes(view),`transparent shared-background view missing ${view}`);

assert.ok(app.includes('function renderTree'),'family tree renderer missing');
assert.ok(app.includes('function drawConnectors'),'coordinate connector renderer missing');
assert.ok(app.includes('renderAll(); bindEvents();'),'runtime must render before interaction binding');
assert.ok(backup.includes('schemaVersion'),'backup must include schema version');
assert.ok(backup.includes('snapshotCurrent'),'restore must snapshot current data');
assert.ok(cloud.includes('drive.appdata'),'Google Drive must use appDataFolder scope');
assert.ok(cloud.includes('resolveConflict'),'cloud conflicts must be explicit');
assert.ok(app.includes('appConfirm'),'destructive actions must use shared confirm');
assert.ok(!app.includes('window.confirm('),'native window.confirm is forbidden');
assert.ok(sw.includes("giaphaphamvan-v47"),'service worker cache version mismatch');
for(const asset of ['/target-ui.css?v=4','/reference-exact.css?v=21','/liquid-menu.css?v=14','/reference-crest.webp?v=2','/heritage-approved-full.webp?v=4','/data.js?v=9']) assert.ok(sw.includes(asset),`service worker missing ${asset}`);
assert.ok(!sw.includes('heritage-approved-top.webp'),'split top background must not be precached');
assert.ok(!sw.includes('heritage-approved-cont.webp'),'split continuation background must not be precached');
assert.ok(!sw.includes('heritage-background.svg'),'broken embedded SVG must not be precached');
assert.ok(sw.includes("cache:'no-store'"),'service worker must bypass stale HTTP artwork cache');
assert.ok(wrangler.includes('"directory": "./public"'),'Wrangler must deploy ./public');
assert.ok(manifest.includes('"theme_color": "#650912"')||manifest.includes('"theme_color": "#65080d"'),'PWA theme must be heritage red');
console.log('Giaphaphamvan single approved heritage + continuous Liquid Glass v47 audit: PASS');
